const moedas = {
  usd: "USD",
  dolar: "USD",
  eur: "EUR",
  euro: "EUR",
  gbp: "GBP",
  libra: "GBP",
  jpy: "JPY",
  yen: "JPY",
  btc: "BTC",
  bitcoin: "BTC",
  ars: "ARS",
  pesoargentino: "ARS",
  cad: "CAD",
  dolarcanadense: "CAD",
  aud: "AUD",
  dolaraustraliano: "AUD",
  chf: "CHF",
  francosuico: "CHF",
  cny: "CNY",
  yuanchines: "CNY",
  mxn: "MXN",
  pesomexicano: "MXN",
  eth: "ETH",
  ethereum: "ETH",
  doge: "DOGE",
  dogecoin: "DOGE",
  ltc: "LTC",
  litecoin: "LTC",
  xrp: "XRP",
  ripple: "XRP",
  sol: "SOL",
  solana: "SOL",
};

export default moedas;
